[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

reqwest = { version = "0.12", features = ["json"] }

inquire = "0.7"
crossterm = "0.28"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
seq-macro = "0.3"
regex = "1.11"
lazy-regex = "3.3"
