[package]
name = "aoc_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
seq-macro.workspace = true
crossterm.workspace = true
chrono.workspace = true
